EnumEntry: Use `def` instead of `lazy val`
Fixes the following exception:
java.lang.AbstractMethodError: org.scalarelational.instruction.ConnectType$Or$.org$powerscala$enum$EnumEntry$$fullName()Ljava/lang/String;